---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplified-onboarding-api
  labels:
    app: simplified-onboarding-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplified-onboarding-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simplified-onboarding-api
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
        - name: simplified-onboarding-api
          image: simplified-onboarding-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          env:
            - name: ANSATTPORTEN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ansattporten-credential
                  key: ANSATTPORTEN_CLIENT_ID
            - name: ANSATTPORTEN_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ansattporten-credential
                  key: ANSATTPORTEN_CLIENT_SECRET