---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-simplified-onboarding-api.yaml
  - service-simplified-onboarding-api.yaml
images:
  - name: simplified-onboarding-api
    newName: eu.gcr.io/digdir-fdk-infra/simplified-onboarding-api
    newTag: $(GIT_COMMIT_SHA)