---
apiVersion: v1
kind: Service
metadata:
  name: simplified-onboarding-api
spec:
  selector:
    app: simplified-onboarding-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort