---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplified-onboarding-api
  labels:
    app: simplified-onboarding-api
spec:
  selector:
    matchLabels:
      app: simplified-onboarding-api
  template:
    spec:
      containers:
        - name: simplified-onboarding-api
          env:
            - name: SIMPLIFIED_ONBOARDING_FRONTEND_URL
              value: https://simplified-onboarding.staging.fellesdatakatalog.digdir.no
            - name: ANSATTPORTEN_LOGIN_BASE_URL
              value: https://login.test.ansattporten.no
            - name: ANSATTPORTEN_API_BASE_URL
              value: https://test.ansattporten.no
            - name: ENV1
              value: test
            - name: ENV1_MASKINPORTEN_API_URL
              value: https://integrasjon-ver2.difi.no
            - name: ENV1_AUTH_SERVER
              value: https://test.maskinporten.no
            - name: ENV2
              value: ver2
            - name: ENV2_MASKINPORTEN_API_URL
              value: https://integrasjon-ver2.difi.no
            - name: ENV2_AUTH_SERVER
              value: https://ver2.maskinporten.no